### PR TITLE
Refactor/update atlas icons

### PR DESCRIPTION
**Pull request by Samsunggora**
https://user-images.githubusercontent.com/55054125/235860199-5402792c-029b-424b-9de3-d93edc9c9194.mp4

### CODE REVIEW

**Comment by Pe5h4** [comment]
@Samsunggora Ok, this looks good. Only thing is to update asab-webui submodule with the changes and also resolve the conflicts

**Comment by Pe5h4** [comment]
@Samsunggora Please, resolve conflicts

**Review by petrKavulok — COMMENTED** [review]
I agree with Franta, otherwise, it looks pretty good! 👍

**Review by Pe5h4 — APPROVED** [review]
@petrKavulok From what I saw it looks good!. Dont forget to update asab-webui when it (asab-webui) will be merged

**Pull request merged**
